version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: achatdb
    
    ports:
      - "3306:3306"

  achat:
    image: azizchniti/chnitiaziz-5bi5-g1-achat:latest
    container_name: chnitiaziz-5bi5-g1-achat
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    

