version: '3'

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarqube-network

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    networks:
      - sonarqube-network

networks:
  sonarqube-network:
